<a href="https://colab.research.google.com/github/Supaporn-Bututham/DWDM21/blob/main/Project_DWDM_(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Project กลุ่ม
* ข้อมูลที่ไปดึงมาจาก 3 แหล่ง
* แสดงวิธีการโหลด
* ความเชื่อมโยงของ 3 ตาราง (index)

Link Drive ที่รวมข้อมูล : https://drive.google.com/drive/folders/1lT7yOhBQxr-_vbsrogIDKaD6ISxta9qK?usp=sharing

In [ ]:
import pandas as pd  # pandas เป็น Package ที่ใช้เกี่ยวกับการจัดการข้อมูลที่เป็นตาราง , เรียกใช้โดยการ import แล้วตามด้วยชื่อ Package

In [ ]:
from google.colab import drive  # เชื่อมต่อกับ google drive ที่เราเก็บข้อมูลไว้
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os # เป็น package ที่เอาไว้จัดการไฟล์และเอาไว้ดูที่มาของไฟล์หรือ path

In [ ]:
path = '/content/drive/My Drive/DWDM2021_DATAPROJECT'    
#ระบุให้ชี้ไปที่โฟลเดอร์ใน google drive ที่เราเซฟไฟล์ไว้ คือ โฟลเดอร์ DWDM2021_DATAPROJECT

## **ชุดข้อมูลที่ 1 รับเรื่องร้องเรียน/แจ้งเบาะแสยาเสพติด**

In [ ]:
data_01 = pd.read_csv(os.path.join(path,'รับเรื่องร้องเรียนยาเสพติด.csv')) # ไฟล์ที่เราต้องการ
data_01 # print data ดูว่ามันหน้าตาเป็นยังไง

    รหัสจังหวัด  ... เปอร์เซ็นต์การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด บุคคล (%)
0            11  ...                                              97.81
1            12  ...                                             100.00
2            13  ...                                              97.26
3            14  ...                                              99.13
4            15  ...                                             100.00
..          ...  ...                                                ...
72           93  ...                                             100.00
73           94  ...                                             100.00
74           95  ...                                             100.00
75           96  ...                                             100.00
76           10  ...                                              93.52

[77 rows x 11 columns]

### คำอธิบายตาราง
* รหัสจังหวัด คือ รหัสจังหวัดที่รับเรื่องร้องเรียน/แจ้งเบาะแสยาเสพติด
* ชื่อจังหวัด คือ ชื่อจังหวัดที่รับเรื่องร้องเรียน/แจ้งเบาะแสยาเสพติด
* เรื่องร้องเรียนและแจ้งเบาะแสยาเสพติดทั้งหมด (เรื่อง) คือ จำนวนของเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติดทั้งหมด (เรื่อง)
* การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติดทั้งหมด (เรื่อง) คือ จำนวนของการดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติดทั้งหมด (เรื่อง)
* เปอร์เซ็นต์การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติดทั้งหมด (%) คือ เปอร์เซ็นต์ของการดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติดทั้งหมด (%)
* เรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด พื้นที่ (เรื่อง) คือ จำนวนของเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด แยกตามพื้นที่ที่รับเรื่องร้องเรียน/แจ้งเบาะแสยาเสพติด (เรื่อง)
* การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด พื้นที่ (เรื่อง) คือ จำนวนของการดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด แยกตามพื้นที่ที่รับเรื่องร้องเรียน/แจ้งเบาะแสยาเสพติด(เรื่อง)
* เปอร์เซ็นต์การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด พื้นที่ (%)คือ เปอร์เซ็นต์ของการดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด แยกตามพื้นที่ที่รับเรื่องร้องเรียน/แจ้งเบาะแสยาเสพติด (%)
* เรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด บุคคล (เรื่อง) คือ จำนวนเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด แยกตามบุคคลที่รับเรื่องร้องเรียน/แจ้งเบาะแสยาเสพติด (เรื่อง)
* การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด บุคคล (เรื่อง) คือ จำนวนการดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด แยกตามบุคคลที่รับเรื่องร้องเรียน/แจ้งเบาะแสยาเสพติด (เรื่อง)
* เปอร์เซ็นต์การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด บุคคล (%) คือ เปอร์เซ็นต์ของการดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด แยกตามบุคคลที่รับเรื่องร้องเรียน/แจ้งเบาะแสยาเสพติด (%)

In [ ]:
data_01 = data_01.sort_values(by=['รหัสจังหวัด'])   # เรียงข้อมูลตามรหัสจังหวัด 
data_01

    รหัสจังหวัด  ... เปอร์เซ็นต์การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด บุคคล (%)
76           10  ...                                              93.52
0            11  ...                                              97.81
1            12  ...                                             100.00
2            13  ...                                              97.26
3            14  ...                                              99.13
..          ...  ...                                                ...
71           92  ...                                             100.00
72           93  ...                                             100.00
73           94  ...                                             100.00
74           95  ...                                             100.00
75           96  ...                                             100.00

[77 rows x 11 columns]

### ตรวจสอบค่า Missing ของตาราง data_01

In [ ]:
data_01.isnull() # ตรงไหนเป็นช่องว่างจะขึ้นว่า True ตรงไหนไม่เป็นช่องว่างจะขึ้นว่า False

    รหัสจังหวัด  ...  เปอร์เซ็นต์การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด บุคคล (%)
76        False  ...                                              False
0         False  ...                                              False
1         False  ...                                              False
2         False  ...                                              False
3         False  ...                                              False
..          ...  ...                                                ...
71        False  ...                                              False
72        False  ...                                              False
73        False  ...                                              False
74        False  ...                                              False
75        False  ...                                              False

[77 rows x 11 columns]

In [ ]:
data_01.isnull().any() # ดูว่าคอลัมน์ไหนมีค่า missing บ้าง สรุปคือทุกคอลัมน์ไม่มีค่า  missing

รหัสจังหวัด                                                                   False
ชื่อจังหวัด                                                                   False
เรื่องร้องเรียนและแจ้งเบาะแสยาเสพติดทั้งหมด (เรื่อง)                          False
การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติดทั้งหมด (เรื่อง)           False
เปอร์เซ็นต์การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติดทั้งหมด (%)     False
เรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด พื้นที่ (เรื่อง)                         False
การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด พื้นที่ (เรื่อง)          False
เปอร์เซ็นต์การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด พื้นที่ (%)    False
เรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด บุคคล (เรื่อง)                           False
การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด บุคคล (เรื่อง)            False
เปอร์เซ็นต์การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด บุคคล (%)      False
dtype: bool

## **ชุดข้อมูลที่ 2 ปริมาณของกลางยาเสพติด**

In [ ]:
data_02 = pd.read_csv(os.path.join(path,'ปริมาณของกลางยาเสพติด.csv')) # ไฟล์ที่เราต้องการ
data_02 # print data ดูว่ามันหน้าตาเป็นยังไง

    รหัสจังหวัด        จังหวัด  ...  โคเคน (กิโลกรัม)  กระท่อม (กิโลกรัม)
0            32       สุรินทร์  ...             0.000            35.07000
1            41       อุดรธานี  ...             0.000             0.26000
2            49       มุกดาหาร  ...             0.000             0.58500
3            47         สกลนคร  ...             0.000            24.53000
4            46      กาฬสินธุ์  ...             0.000             0.00000
..          ...            ...  ...               ...                 ...
72           92           ตรัง  ...             0.000          1772.45500
73           93         พัทลุง  ...             0.000          1242.31250
74           94        ปัตตานี  ...             0.000          5950.30800
75           95           ยะลา  ...             0.000          4043.89700
76           10  กรุงเทพมหานคร  ...             0.049          2755.81611

[77 rows x 9 columns]

### คำอธิบายตาราง
* รหัสจังหวัด คือ รหัสของจังหวัดที่พบของกลางยาเสพติด
* จังหวัด คือ ชื่อของจังหวัดที่พบของกลางยาเสพติด
* ยาบ้า (เม็ด) คือ ปริมาณของยาบ้าที่พบในแต่ละจังหวัด (เม็ด)
* ไอซ์ (กิโลกรัม) คือ ปริมาณของยาไอซ์ที่พบในแต่ละจังหวัด (กิโลกรัม)
* กัญชาแห้ง (กิโลกรัม) คือ ปริมาณของกัญชาแห้งที่พบในแต่ละจังหวัด (กิโลกรัม)
* เฮโรอีน (กิโลกรัม) คือ ปริมาณของเฮโรอีนที่พบในแต่ละจังหวัด (กิโลกรัม)
* คีตามีน (กิโลกรัม) คือ ปริมาณของคีตามีนที่พบในแต่ละจังหวัด (กิโลกรัม)
* โคเคน (กิโลกรัม) คือ ปริมาณของโคเคนที่พบในแต่ละจังหวัด (กิโลกรัม)
* กระท่อม (กิโลกรัม) คือ ปริมาณของกระท่อมที่พบในแต่ละจังหวัด (กิโลกรัม)

In [ ]:
data_02 = data_02.sort_values(by=['รหัสจังหวัด'])  # เรียงข้อมูลตามรหัสจังหวัด 
data_02

    รหัสจังหวัด          จังหวัด  ...  โคเคน (กิโลกรัม)  กระท่อม (กิโลกรัม)
76           10    กรุงเทพมหานคร  ...             0.049          2755.81611
24           11      สมุทรปราการ  ...             0.000           332.85821
25           12          นนทบุรี  ...             0.030           626.33734
26           13         ปทุมธานี  ...             0.000           981.02860
27           14  พระนครศรีอยุธยา  ...             0.000           932.65946
..          ...              ...  ...               ...                 ...
72           92             ตรัง  ...             0.000          1772.45500
73           93           พัทลุง  ...             0.000          1242.31250
74           94          ปัตตานี  ...             0.000          5950.30800
75           95             ยะลา  ...             0.000          4043.89700
69           96         นราธิวาส  ...             0.000          5569.70900

[77 rows x 9 columns]

### ตรวจสอบค่า Missing ของตาราง data_02

In [ ]:
data_02.isnull() # ตรงไหนเป็นช่องว่างจะขึ้นว่า True ตรงไหนไม่เป็นช่องว่างจะขึ้นว่า False

    รหัสจังหวัด  จังหวัด  ...  โคเคน (กิโลกรัม)  กระท่อม (กิโลกรัม)
76        False    False  ...             False               False
24        False    False  ...             False               False
25        False    False  ...             False               False
26        False    False  ...             False               False
27        False    False  ...             False               False
..          ...      ...  ...               ...                 ...
72        False    False  ...             False               False
73        False    False  ...             False               False
74        False    False  ...             False               False
75        False    False  ...             False               False
69        False    False  ...             False               False

[77 rows x 9 columns]

In [ ]:
data_02.isnull().any() # ดูว่าคอลัมน์ไหนมีค่า missing บ้าง สรุปคือทุกคอลัมน์ไม่มีค่า  missing

รหัสจังหวัด             False
จังหวัด                 False
ยาบ้า (เม็ด)            False
ไอซ์ (กิโลกรัม)         False
กัญชาแห้ง (กิโลกรัม)    False
เฮโรอีน (กิโลกรัม)      False
คีตามีน (กิโลกรัม)      False
โคเคน (กิโลกรัม)        False
กระท่อม (กิโลกรัม)      False
dtype: bool

## **ชุดข้อมูลที่ 3 จำนวนคดี ผู้ต้องหาคดียาเสพติด**

In [ ]:
data_03 = pd.read_csv(os.path.join(path,'คดีผู้องหาคดียาเสพติด.csv')) # ไฟล์ที่เราต้องการ
data_03 # print data ดูว่ามันหน้าตาเป็นยังไง

    ปีงบประมาณ  ...  จำนวนผู้ต้องหาคดี 5 ข้อหาหลัก (คน)
0         2563  ...                                1198
1         2563  ...                                 596
2         2563  ...                                1433
3         2563  ...                                 913
4         2563  ...                                1857
..         ...  ...                                 ...
72        2563  ...                                3043
73        2563  ...                                1619
74        2563  ...                                2164
75        2563  ...                                 834
76        2563  ...                                 881

[77 rows x 22 columns]

### คำอธิบายตาราง
* ปีงบประมาณ คือ ปีงบประมาณของจำนวนคดีและจำนวนผู้ต้องหาคดียาเสพติด
* รหัสจังหวัด คือ รหัสของจังหวัดที่มีคดียาเสพติดและผู้ต้องหาคดียาเสพติด
* จำนวนคดีทั้งหมด (คดี) คือ จำนวนของคดียาเสพติดทั้งหมด (คดี)
* จำนวนผู้ต้องหาทั้งหมด (คน) คือ จำนวนของผู้ต้องหาคดียาเสพติดทั้งหมด (คน)
* จำนวนคดีเสพ (คดี) คือ จำนวนคดียาเสพติดข้อหาเสพยาเสพติดทั้งหมด (คดี)
* จำนวนผู้ต้องหาคดีเสพ (คน) คือ จำนวนผู้ต้องหาคดียาเสพติดข้อหาเสพยาเสพติดทั้งหมด (คน)
* จำนวนคดีครอบครอง (คดี) คือ จำนวนคดียาเสพติดข้อหาครอบครองยาเสพติดทั้งหมด (คดี)
* จำนวนผู้ต้องหาคดีครอบครอง (คน) คือ จำนวนของผู้ต้องหาคดียาเสพติดข้อหาครอบครองยาเสพติดทั้งหมด (คน)
* จำนวนคดีครอบครองเพื่อจำหน่าย (คดี) คือ จำนวนคดียาเสพติดข้อหาครอบครองเพื่อจำหน่ายยาเสพติดทั้งหมด (คดี)
* จำนวนผู้ต้องหาคดีครอบครองเพื่อจำหน่าย (คน) คือ จำนวนผู้ต้องหาคดียาเสพติดข้อหาครอบครองเพื่อจำหน่ายยาเสพติดทั้งหมด (คน)
* จำนวนคดีจำหน่าย (คดี) คือ จำนวนคดียาเสพติดข้อหาจำหน่ายยาเสพติดทั้งหมด (คดี)
* จำนวนผู้ต้องหาคดีจำหน่าย (คน) คือ จำนวนผู้ต้องหาคดียาเสพติดข้อหาจำหน่ายยาเสพติดทั้งหมด (คน)
* จำนวนคดีผลิต (คดี) คือ จำนวนคดียาเสพติดข้อหาผลิตยาเสพติดทั้งหมด (คดี)
* จำนวนผู้ต้องหาคดีผลิต (คน) คือ จำนวนผู้ต้องหาคดียาเสพติดข้อหาผลิตยาเสพติดทั้งหมด (คน)
* จำนวนคดีนำเข้า (คดี) คือ จำนวนคดียาเสพติดข้อหานำเข้ายาเสพติดทั้งหมด (คดี)
* จำนวนผู้ต้องหาคดีนำเข้า (คน) คือ จำนวนผู้ต้องหาคดียาเสพติดข้อหานำเข้ายาเสพติดทั้งหมด (คน)
* จำนวนคดีส่งออก (คดี) คือ จำนวนคดียาเสพติดข้อหาส่งออกยาเสพติดทั้งหมด (คดี)
* จำนวนผู้ต้องหาคดีส่งออก (คน) คือ จำนวนผู้ต้องหาคดียาเสพติดข้อหาส่งออกยาเสพติดทั้งหมด (คน)
* จำนวนคดีสมคบ (คดี) คือ จำนวนคดียาเสพติดข้อหาสมคบคิดทั้งหมด (คดี)
* จำนวนผู้ต้องหาคดีสมคบ (คน) คือ จำนวนผู้ต้องหาคดียาเสพติดข้อหาสมคบคิดทั้งหมด (คน)
* จำนวนคดี 5 ข้อหาหลัก (คดี) คือ จำนวนคดียาเสพติด 5 ข้อหาหลัก คือ ครอบครองเพื่อจำหน่าย, จำหน่าย, ผลิต, นำเข้า และส่งออกทั้งหมด (คดี)
* จำนวนผู้ต้องหาคดี 5 ข้อหาหลัก (คน) คือ จำนวนผู้ต้องหาคดียาเสพติด 5 ข้อหาหลัก คือ ครอบครองเพื่อจำหน่าย, จำหน่าย, ผลิต, นำเข้า และส่งออกทั้งหมด (คดี)

In [ ]:
data_03 = data_03.sort_values(by=['รหัสจังหวัด'])  # เรียงข้อมูลตามรหัสจังหวัด 
data_03

    ปีงบประมาณ  ...  จำนวนผู้ต้องหาคดี 5 ข้อหาหลัก (คน)
47        2563  ...                                5685
53        2563  ...                                2999
49        2563  ...                                1448
50        2563  ...                                1873
51        2563  ...                                1650
..         ...  ...                                 ...
40        2563  ...                                1346
43        2563  ...                                1208
42        2563  ...                                1624
44        2563  ...                                1161
41        2563  ...                                1230

[77 rows x 22 columns]

### ตรวจสอบค่า Missing ของตาราง data_03

In [ ]:
data_03.isnull() # ตรงไหนเป็นช่องว่างจะขึ้นว่า True ตรงไหนไม่เป็นช่องว่างจะขึ้นว่า False

    ปีงบประมาณ  ...  จำนวนผู้ต้องหาคดี 5 ข้อหาหลัก (คน)
47       False  ...                               False
53       False  ...                               False
49       False  ...                               False
50       False  ...                               False
51       False  ...                               False
..         ...  ...                                 ...
40       False  ...                               False
43       False  ...                               False
42       False  ...                               False
44       False  ...                               False
41       False  ...                               False

[77 rows x 22 columns]

In [ ]:
data_03.isnull().any() # ดูว่าคอลัมน์ไหนมีค่า missing บ้าง สรุปคือบางคอลัมน์มีค่า  missing  ดังนั้นจะต้องแก้ missing ก่อน

ปีงบประมาณ                                    False
รหัสจังหวัด                                   False
จำนวนคดีทั้งหมด (คดี)                         False
จำนวนผู้ต้องหาทั้งหมด (คน)                    False
จำนวนคดีเสพ (คดี)                             False
จำนวนผู้ต้องหาคดีเสพ (คน)                     False
จำนวนคดีครอบครอง (คดี)                        False
จำนวนผู้ต้องหาคดีครอบครอง (คน)                False
จำนวนคดีครอบครองเพื่อจำหน่าย (คดี)            False
จำนวนผู้ต้องหาคดีครอบครองเพื่อจำหน่าย (คน)    False
จำนวนคดีจำหน่าย (คดี)                         False
จำนวนผู้ต้องหาคดีจำหน่าย (คน)                 False
จำนวนคดีผลิต (คดี)                            False
จำนวนผู้ต้องหาคดีผลิต (คน)                    False
จำนวนคดีนำเข้า (คดี)                          False
จำนวนผู้ต้องหาคดีนำเข้า (คน)                  False
จำนวนคดีส่งออก (คดี)                          False
จำนวนผู้ต้องหาคดีส่งออก (คน)                  False
จำนวนคดีสมคบ (คดี)                            False
จำนวนผู้ต้องหาคดีสมคบ (คน)                    False
จำนวนคดี 5 ข้อหาหลัก (คดี)                    False
จำนวนผู้ต้องหาคดี 5 ข้อหาหลัก (คน)            False
dtype: bool

In [ ]:
data_03_dropped = data_03.dropna() # แก้ค่า missing โดยใช้ .dropna()
data_03_dropped

    ปีงบประมาณ  ...  จำนวนผู้ต้องหาคดี 5 ข้อหาหลัก (คน)
47        2563  ...                                5685
53        2563  ...                                2999
49        2563  ...                                1448
50        2563  ...                                1873
51        2563  ...                                1650
..         ...  ...                                 ...
40        2563  ...                                1346
43        2563  ...                                1208
42        2563  ...                                1624
44        2563  ...                                1161
41        2563  ...                                1230

[77 rows x 22 columns]

In [ ]:
data_03_dropped.shape # ตรวจสอบขนาดของข้อมูลหลังจากที่ .dropna()

(77, 22)

In [ ]:
data_03.shape # ตรวจสอบขนาดของข้อมูลก่อนที่จะ .dropna()

(77, 22)

In [ ]:
### function หา % ของข้อมูลที่จะหายไปถ้า .dropna()
def loss_data(data):
    before = data.shape[0]
    after = data.dropna().shape[0]
    c = before - after
    print(f'size before drop = {before}')
    print(f'size after drop = {after}')
    print(f'we loss {c*100/before} % of data')

In [ ]:
loss_data(data_03) # จะเห็นได้ว่าหลังจากที่ .dropna() ข้อมูลหายไป 55.84 % ซึ่งเป็นจำนวนมาก ดังนั้นจึงเลือกที่จะแก้ค่า missing ด้วยวิธีอื่น

size before drop = 77
size after drop = 77
we loss 0.0 % of data

In [ ]:
data_03.isnull().any() # ดูว่าคอลัมน์ไหนมีค่า missing บ้าง จะเห็นว่ามีคอลัมน์ที่มีค่า missing อยู่ทั้งหมด 4 คอลัมน์ คือ จำนวนคดีนำเข้า (คดี), จำนวนผู้ต้องหาคดีนำเข้า (คน)
# จำนวนคดีสมคบ (คดี) และ จำนวนผู้ต้องหาคดีสมคบ (คน) ดังนั้นจะทำการแก้ค่า missing ทั้ง 4 คอลัมน์นี้

ปีงบประมาณ                                    False
รหัสจังหวัด                                   False
จำนวนคดีทั้งหมด (คดี)                         False
จำนวนผู้ต้องหาทั้งหมด (คน)                    False
จำนวนคดีเสพ (คดี)                             False
จำนวนผู้ต้องหาคดีเสพ (คน)                     False
จำนวนคดีครอบครอง (คดี)                        False
จำนวนผู้ต้องหาคดีครอบครอง (คน)                False
จำนวนคดีครอบครองเพื่อจำหน่าย (คดี)            False
จำนวนผู้ต้องหาคดีครอบครองเพื่อจำหน่าย (คน)    False
จำนวนคดีจำหน่าย (คดี)                         False
จำนวนผู้ต้องหาคดีจำหน่าย (คน)                 False
จำนวนคดีผลิต (คดี)                            False
จำนวนผู้ต้องหาคดีผลิต (คน)                    False
จำนวนคดีนำเข้า (คดี)                          False
จำนวนผู้ต้องหาคดีนำเข้า (คน)                  False
จำนวนคดีส่งออก (คดี)                          False
จำนวนผู้ต้องหาคดีส่งออก (คน)                  False
จำนวนคดีสมคบ (คดี)                            False
จำนวนผู้ต้องหาคดีสมคบ (คน)                    False
จำนวนคดี 5 ข้อหาหลัก (คดี)                    False
จำนวนผู้ต้องหาคดี 5 ข้อหาหลัก (คน)            False
dtype: bool

In [ ]:
data_03[['จำนวนคดีนำเข้า (คดี)']] = data_03[['จำนวนคดีนำเข้า (คดี)']].fillna('0')  # เติมค่า missing เป็น 0 เนื่องจากในตารางเป็นค่าว่างซึ่งอาจจะแปลว่าไม่มีจำนวนคดียาเสพติดข้อหานำเข้ายาเสพติด

In [ ]:
data_03.isnull().any() # ดูว่าคอลัมน์ไหนมีค่า missing บ้าง จะเห็นว่าคอลัมน์ของ จำนวนคดีนำเข้า (คดี) เป็น False แสดงว่าไม่มีค่า missing

ปีงบประมาณ                                    False
รหัสจังหวัด                                   False
จำนวนคดีทั้งหมด (คดี)                         False
จำนวนผู้ต้องหาทั้งหมด (คน)                    False
จำนวนคดีเสพ (คดี)                             False
จำนวนผู้ต้องหาคดีเสพ (คน)                     False
จำนวนคดีครอบครอง (คดี)                        False
จำนวนผู้ต้องหาคดีครอบครอง (คน)                False
จำนวนคดีครอบครองเพื่อจำหน่าย (คดี)            False
จำนวนผู้ต้องหาคดีครอบครองเพื่อจำหน่าย (คน)    False
จำนวนคดีจำหน่าย (คดี)                         False
จำนวนผู้ต้องหาคดีจำหน่าย (คน)                 False
จำนวนคดีผลิต (คดี)                            False
จำนวนผู้ต้องหาคดีผลิต (คน)                    False
จำนวนคดีนำเข้า (คดี)                          False
จำนวนผู้ต้องหาคดีนำเข้า (คน)                  False
จำนวนคดีส่งออก (คดี)                          False
จำนวนผู้ต้องหาคดีส่งออก (คน)                  False
จำนวนคดีสมคบ (คดี)                            False
จำนวนผู้ต้องหาคดีสมคบ (คน)                    False
จำนวนคดี 5 ข้อหาหลัก (คดี)                    False
จำนวนผู้ต้องหาคดี 5 ข้อหาหลัก (คน)            False
dtype: bool

In [ ]:
data_03[['จำนวนผู้ต้องหาคดีนำเข้า (คน)']] = data_03[['จำนวนผู้ต้องหาคดีนำเข้า (คน)']].fillna('0') # เติมค่า missing เป็น 0 เนื่องจากในตารางเป็นค่าว่างซึ่งอาจจะแปลว่าไม่มีจำนวนผู้ต้องหาคดียาเสพติดข้อหานำเข้ายาเสพติด

In [ ]:
data_03.isnull().any() # ดูว่าคอลัมน์ไหนมีค่า missing บ้าง จะเห็นว่า คอลัมน์ของ จำนวนผู้ต้องหาคดีนำเข้า (คน) เป็น False แสดงว่าไม่มีค่า missing

ปีงบประมาณ                                    False
รหัสจังหวัด                                   False
จำนวนคดีทั้งหมด (คดี)                         False
จำนวนผู้ต้องหาทั้งหมด (คน)                    False
จำนวนคดีเสพ (คดี)                             False
จำนวนผู้ต้องหาคดีเสพ (คน)                     False
จำนวนคดีครอบครอง (คดี)                        False
จำนวนผู้ต้องหาคดีครอบครอง (คน)                False
จำนวนคดีครอบครองเพื่อจำหน่าย (คดี)            False
จำนวนผู้ต้องหาคดีครอบครองเพื่อจำหน่าย (คน)    False
จำนวนคดีจำหน่าย (คดี)                         False
จำนวนผู้ต้องหาคดีจำหน่าย (คน)                 False
จำนวนคดีผลิต (คดี)                            False
จำนวนผู้ต้องหาคดีผลิต (คน)                    False
จำนวนคดีนำเข้า (คดี)                          False
จำนวนผู้ต้องหาคดีนำเข้า (คน)                  False
จำนวนคดีส่งออก (คดี)                          False
จำนวนผู้ต้องหาคดีส่งออก (คน)                  False
จำนวนคดีสมคบ (คดี)                            False
จำนวนผู้ต้องหาคดีสมคบ (คน)                    False
จำนวนคดี 5 ข้อหาหลัก (คดี)                    False
จำนวนผู้ต้องหาคดี 5 ข้อหาหลัก (คน)            False
dtype: bool

In [ ]:
data_03[['จำนวนคดีสมคบ (คดี)']] = data_03[['จำนวนคดีสมคบ (คดี)']].fillna('0')  # เติมค่า missing เป็น 0 เนื่องจากในตารางเป็นค่าว่างซึ่งอาจจะแปลว่าไม่มีจำนวนคดียาเสพติดข้อหาสมคบคิด

In [ ]:
data_03.isnull().any() # ดูว่าคอลัมน์ไหนมีค่า missing บ้าง จะเห็นว่า คอลัมน์ของ จำนวนคดีสมคบ (คดี) เป็น False แสดงว่าไม่มีค่า missing

ปีงบประมาณ                                    False
รหัสจังหวัด                                   False
จำนวนคดีทั้งหมด (คดี)                         False
จำนวนผู้ต้องหาทั้งหมด (คน)                    False
จำนวนคดีเสพ (คดี)                             False
จำนวนผู้ต้องหาคดีเสพ (คน)                     False
จำนวนคดีครอบครอง (คดี)                        False
จำนวนผู้ต้องหาคดีครอบครอง (คน)                False
จำนวนคดีครอบครองเพื่อจำหน่าย (คดี)            False
จำนวนผู้ต้องหาคดีครอบครองเพื่อจำหน่าย (คน)    False
จำนวนคดีจำหน่าย (คดี)                         False
จำนวนผู้ต้องหาคดีจำหน่าย (คน)                 False
จำนวนคดีผลิต (คดี)                            False
จำนวนผู้ต้องหาคดีผลิต (คน)                    False
จำนวนคดีนำเข้า (คดี)                          False
จำนวนผู้ต้องหาคดีนำเข้า (คน)                  False
จำนวนคดีส่งออก (คดี)                          False
จำนวนผู้ต้องหาคดีส่งออก (คน)                  False
จำนวนคดีสมคบ (คดี)                            False
จำนวนผู้ต้องหาคดีสมคบ (คน)                    False
จำนวนคดี 5 ข้อหาหลัก (คดี)                    False
จำนวนผู้ต้องหาคดี 5 ข้อหาหลัก (คน)            False
dtype: bool

In [ ]:
data_03[['จำนวนผู้ต้องหาคดีสมคบ (คน)']] = data_03[['จำนวนผู้ต้องหาคดีสมคบ (คน)']].fillna('0')  # เติมค่า missing เป็น 0 เนื่องจากในตารางเป็นค่าว่างซึ่งอาจจะแปลว่าไม่มีจำนวนผู้ต้องหาคดียาเสพติดข้อหาสมคบคิด

In [ ]:
data_03.isnull().any() # ดูว่าคอลัมน์ไหนมีค่า missing บ้าง จะเห็นว่า คอลัมน์ของ จำนวนผู้ต้องหาคดีสมคบ (คน) เป็น False แสดงว่าไม่มีค่า missing

ปีงบประมาณ                                    False
รหัสจังหวัด                                   False
จำนวนคดีทั้งหมด (คดี)                         False
จำนวนผู้ต้องหาทั้งหมด (คน)                    False
จำนวนคดีเสพ (คดี)                             False
จำนวนผู้ต้องหาคดีเสพ (คน)                     False
จำนวนคดีครอบครอง (คดี)                        False
จำนวนผู้ต้องหาคดีครอบครอง (คน)                False
จำนวนคดีครอบครองเพื่อจำหน่าย (คดี)            False
จำนวนผู้ต้องหาคดีครอบครองเพื่อจำหน่าย (คน)    False
จำนวนคดีจำหน่าย (คดี)                         False
จำนวนผู้ต้องหาคดีจำหน่าย (คน)                 False
จำนวนคดีผลิต (คดี)                            False
จำนวนผู้ต้องหาคดีผลิต (คน)                    False
จำนวนคดีนำเข้า (คดี)                          False
จำนวนผู้ต้องหาคดีนำเข้า (คน)                  False
จำนวนคดีส่งออก (คดี)                          False
จำนวนผู้ต้องหาคดีส่งออก (คน)                  False
จำนวนคดีสมคบ (คดี)                            False
จำนวนผู้ต้องหาคดีสมคบ (คน)                    False
จำนวนคดี 5 ข้อหาหลัก (คดี)                    False
จำนวนผู้ต้องหาคดี 5 ข้อหาหลัก (คน)            False
dtype: bool

In [ ]:
data_01.shape # ตรวจสอบขนาดของข้อมูล data_01

(77, 11)

In [ ]:
data_02.shape # ตรวจสอบขนาดของข้อมูล data_02

(77, 9)

In [ ]:
data_03.shape # ตรวจสอบขนาดของข้อมูล data_03

(77, 22)

## **เชื่อมต่อตาราง**

In [ ]:
# เชื่อมต่อตาราง data_03 (จำนวนคดี ผู้ต้องหาคดียาเสพติด) กับ data_01 (รับเรื่องร้องเรียน/แจ้งเบาะแสยาเสพติด)
merge_2table = data_03.merge(data_01,how='left', left_on='รหัสจังหวัด',right_on='รหัสจังหวัด')
merge_2table

    ปีงบประมาณ  ...  เปอร์เซ็นต์การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด บุคคล (%)
0         2563  ...                                              93.52
1         2563  ...                                              97.81
2         2563  ...                                             100.00
3         2563  ...                                              97.26
4         2563  ...                                              99.13
..         ...  ...                                                ...
72        2563  ...                                             100.00
73        2563  ...                                             100.00
74        2563  ...                                             100.00
75        2563  ...                                             100.00
76        2563  ...                                             100.00

[77 rows x 32 columns]

### ตรวจสอบค่า Missing ของตาราง 2 ตารางที่เชื่อมต่อกันแล้ว

In [ ]:
merge_2table.isnull() # ตรงไหนเป็นช่องว่างจะขึ้นว่า True ตรงไหนไม่เป็นช่องว่างจะขึ้นว่า False

    ปีงบประมาณ  ...  เปอร์เซ็นต์การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด บุคคล (%)
0        False  ...                                              False
1        False  ...                                              False
2        False  ...                                              False
3        False  ...                                              False
4        False  ...                                              False
..         ...  ...                                                ...
72       False  ...                                              False
73       False  ...                                              False
74       False  ...                                              False
75       False  ...                                              False
76       False  ...                                              False

[77 rows x 32 columns]

In [ ]:
merge_2table.isnull().any() # ดูว่าคอลัมน์ไหนมีค่า missing บ้าง สรุปคือไม่มีคอลัมน์ไหนที่มีค่า missing

ปีงบประมาณ                                                                    False
รหัสจังหวัด                                                                   False
จำนวนคดีทั้งหมด (คดี)                                                         False
จำนวนผู้ต้องหาทั้งหมด (คน)                                                    False
จำนวนคดีเสพ (คดี)                                                             False
จำนวนผู้ต้องหาคดีเสพ (คน)                                                     False
จำนวนคดีครอบครอง (คดี)                                                        False
จำนวนผู้ต้องหาคดีครอบครอง (คน)                                                False
จำนวนคดีครอบครองเพื่อจำหน่าย (คดี)                                            False
จำนวนผู้ต้องหาคดีครอบครองเพื่อจำหน่าย (คน)                                    False
จำนวนคดีจำหน่าย (คดี)                                                         False
จำนวนผู้ต้องหาคดีจำหน่าย (คน)                                                 False
จำนวนคดีผลิต (คดี)                                                            False
จำนวนผู้ต้องหาคดีผลิต (คน)                                                    False
จำนวนคดีนำเข้า (คดี)                                                          False
จำนวนผู้ต้องหาคดีนำเข้า (คน)                                                  False
จำนวนคดีส่งออก (คดี)                                                          False
จำนวนผู้ต้องหาคดีส่งออก (คน)                                                  False
จำนวนคดีสมคบ (คดี)                                                            False
จำนวนผู้ต้องหาคดีสมคบ (คน)                                                    False
จำนวนคดี 5 ข้อหาหลัก (คดี)                                                    False
จำนวนผู้ต้องหาคดี 5 ข้อหาหลัก (คน)                                            False
ชื่อจังหวัด                                                                   False
เรื่องร้องเรียนและแจ้งเบาะแสยาเสพติดทั้งหมด (เรื่อง)                          False
การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติดทั้งหมด (เรื่อง)           False
เปอร์เซ็นต์การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติดทั้งหมด (%)     False
เรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด พื้นที่ (เรื่อง)                         False
การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด พื้นที่ (เรื่อง)          False
เปอร์เซ็นต์การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด พื้นที่ (%)    False
เรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด บุคคล (เรื่อง)                           False
การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด บุคคล (เรื่อง)            False
เปอร์เซ็นต์การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด บุคคล (%)      False
dtype: bool

In [ ]:
# เชื่อมต่อตาราง data_03 (จำนวนคดี ผู้ต้องหาคดียาเสพติด) กับ data_01 (รับเรื่องร้องเรียน/แจ้งเบาะแสยาเสพติด) กับ data_02 (ปริมาณของกลางยาเสพติด)
merge_3table = merge_2table.merge(data_02,how='left', left_on='รหัสจังหวัด',right_on='รหัสจังหวัด')
merge_3table

    ปีงบประมาณ  รหัสจังหวัด  ...  โคเคน (กิโลกรัม)  กระท่อม (กิโลกรัม)
0         2563           10  ...             0.049          2755.81611
1         2563           11  ...             0.000           332.85821
2         2563           12  ...             0.030           626.33734
3         2563           13  ...             0.000           981.02860
4         2563           14  ...             0.000           932.65946
..         ...          ...  ...               ...                 ...
72        2563           92  ...             0.000          1772.45500
73        2563           93  ...             0.000          1242.31250
74        2563           94  ...             0.000          5950.30800
75        2563           95  ...             0.000          4043.89700
76        2563           96  ...             0.000          5569.70900

[77 rows x 40 columns]

### ตรวจสอบค่า Missing ของตาราง 3 ตารางที่เชื่อมต่อกันแล้ว

In [ ]:
merge_3table.isnull() # ตรงไหนเป็นช่องว่างจะขึ้นว่า True ตรงไหนไม่เป็นช่องว่างจะขึ้นว่า False

    ปีงบประมาณ  รหัสจังหวัด  ...  โคเคน (กิโลกรัม)  กระท่อม (กิโลกรัม)
0        False        False  ...             False               False
1        False        False  ...             False               False
2        False        False  ...             False               False
3        False        False  ...             False               False
4        False        False  ...             False               False
..         ...          ...  ...               ...                 ...
72       False        False  ...             False               False
73       False        False  ...             False               False
74       False        False  ...             False               False
75       False        False  ...             False               False
76       False        False  ...             False               False

[77 rows x 40 columns]

In [ ]:
merge_3table.isnull().any()  # ดูว่าคอลัมน์ไหนมีค่า missing บ้าง สรุปคือไม่มีคอลัมน์ไหนที่มีค่า missing

ปีงบประมาณ                                                                    False
รหัสจังหวัด                                                                   False
จำนวนคดีทั้งหมด (คดี)                                                         False
จำนวนผู้ต้องหาทั้งหมด (คน)                                                    False
จำนวนคดีเสพ (คดี)                                                             False
จำนวนผู้ต้องหาคดีเสพ (คน)                                                     False
จำนวนคดีครอบครอง (คดี)                                                        False
จำนวนผู้ต้องหาคดีครอบครอง (คน)                                                False
จำนวนคดีครอบครองเพื่อจำหน่าย (คดี)                                            False
จำนวนผู้ต้องหาคดีครอบครองเพื่อจำหน่าย (คน)                                    False
จำนวนคดีจำหน่าย (คดี)                                                         False
จำนวนผู้ต้องหาคดีจำหน่าย (คน)                                                 False
จำนวนคดีผลิต (คดี)                                                            False
จำนวนผู้ต้องหาคดีผลิต (คน)                                                    False
จำนวนคดีนำเข้า (คดี)                                                          False
จำนวนผู้ต้องหาคดีนำเข้า (คน)                                                  False
จำนวนคดีส่งออก (คดี)                                                          False
จำนวนผู้ต้องหาคดีส่งออก (คน)                                                  False
จำนวนคดีสมคบ (คดี)                                                            False
จำนวนผู้ต้องหาคดีสมคบ (คน)                                                    False
จำนวนคดี 5 ข้อหาหลัก (คดี)                                                    False
จำนวนผู้ต้องหาคดี 5 ข้อหาหลัก (คน)                                            False
ชื่อจังหวัด                                                                   False
เรื่องร้องเรียนและแจ้งเบาะแสยาเสพติดทั้งหมด (เรื่อง)                          False
การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติดทั้งหมด (เรื่อง)           False
เปอร์เซ็นต์การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติดทั้งหมด (%)     False
เรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด พื้นที่ (เรื่อง)                         False
การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด พื้นที่ (เรื่อง)          False
เปอร์เซ็นต์การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด พื้นที่ (%)    False
เรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด บุคคล (เรื่อง)                           False
การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด บุคคล (เรื่อง)            False
เปอร์เซ็นต์การดำเนินการต่อเรื่องร้องเรียนและแจ้งเบาะแสยาเสพติด บุคคล (%)      False
จังหวัด                                                                       False
ยาบ้า (เม็ด)                                                                  False
ไอซ์ (กิโลกรัม)                                                               False
กัญชาแห้ง (กิโลกรัม)                                                          False
เฮโรอีน (กิโลกรัม)                                                            False
คีตามีน (กิโลกรัม)                                                            False
โคเคน (กิโลกรัม)                                                              False
กระท่อม (กิโลกรัม)                                                            False
dtype: bool