<a href="https://colab.research.google.com/github/Supaporn-Bututham/DWDM21/blob/main/Project_DWDM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd  # pandas เป็น Package ที่ใช้เกี่ยวกับการจัดการข้อมูลที่เป็นตาราง , เรียกใช้โดยการ import แล้วตามด้วยชื่อ Package

In [ ]:
from google.colab import drive  # เชื่อมต่อกับ google drive ที่เราเก็บข้อมูลไว้
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os # เป็น package ที่เอาไว้จัดการไฟล์และเอาไว้ดูที่มาของไฟล์หรือ path

In [ ]:
path = '/content/drive/My Drive/DWDM2021_DATAPROJECT' 
data_straffic60 = pd.read_csv(os.path.join(path,'straffic60.csv')) # ไฟล์ที่เราต้องการ
data_straffic60 # print data ดูว่ามันหน้าตาเป็นยังไง

      ทางหลวงสาย  ตอนควบคุม  ...                         แขวงการทาง          จังหวัด
0              1        102  ...                         ขท.กรุงเทพ    กรุงเทพมหานคร
1              1        201  ...                        ขท.ปทุมธานี         ปทุมธานี
2              1        202  ...                        ขท.ปทุมธานี  พระนครศรีอยุธยา
3              1        300  ...                          ขท.อยุธยา  พระนครศรีอยุธยา
4              1        300  ...                          ขท.อยุธยา  พระนครศรีอยุธยา
...          ...        ...  ...                                ...              ...
2686        4347        100  ...                            ขท.ตรัง             ตรัง
2687        4348        100  ...                          ขท.กระบี่             ตรัง
2688        4349        100  ...      ขท.สุราษฎร์ธานีที่ 1 (พุนพิน)     สุราษฎร์ธานี
2689        4350        100  ...  ขท.สุราษฎร์ธานีที่ 2 (กาญจนดิษฐ์)     สุราษฎร์ธานี
2690        4363        100  ...                            ขท.ยะลา             ยะลา

[2691 rows x 20 columns]

In [ ]:
data_straffic60.isnull() # ตรงไหนเป็นช่องว่างจะขึ้นว่า True ตรงไหนไม่เป็นช่องว่างจะขึ้นว่า False

      ทางหลวงสาย  ตอนควบคุม  ...  แขวงการทาง  จังหวัด
0          False      False  ...       False    False
1          False      False  ...       False    False
2          False      False  ...       False    False
3          False      False  ...       False    False
4          False      False  ...       False    False
...          ...        ...  ...         ...      ...
2686       False      False  ...       False    False
2687       False      False  ...       False    False
2688       False      False  ...       False    False
2689       False      False  ...       False    False
2690       False      False  ...       False    False

[2691 rows x 20 columns]

In [ ]:
data_straffic60.isnull().any() # ดูว่าคอลัมน์ไหนมีค่า missing บ้าง

ทางหลวงสาย                              False
ตอนควบคุม                               False
ชื่อสายทาง                              False
จุดสำรวจ                                False
รถยนต์นั่ง (ไม่เกิน 7 คน)               False
รถยนต์นั่ง (เกิน 7 คน)                  False
รถโดยสารขนาดเล็ก                        False
รถโดยสารขนาดกลาง                        False
รถโดยสารขนาดใหญ่                        False
   รถบรรทุกขนาดเล็ก    ( 4 ล้อ)         False
รถบรรทุกขนาด 2 เพลา  (6 ล้อ)            False
     รถบรรทุกขนาด 3 เพลา (10 ล้อ)       False
   รถบรรทุกพ่วง  (มากกว่า 3 เพลา)       False
   รถบรรทุกกึ่งพ่วง (มากกว่า 3 เพลา)    False
รวม                                     False
   % ของยานยนต์หนัก                     False
จักรยาน 2 ล้อ และ จักรยาน 3 ล้อ         False
สามล้อเครื่องและจักรยานยนต์             False
แขวงการทาง                              False
จังหวัด                                 False
dtype: bool

In [ ]:
data_straffic61 = pd.read_csv(os.path.join(path,'straffic61.csv')) # ไฟล์ที่เราต้องการ
data_straffic61 # print data ดูว่ามันหน้าตาเป็นยังไง

     ทางหลวงสาย  ตอนควบคุม  ...           แขวงทางหลวง          จังหวัด
0             1        102  ...            ขท.กรุงเทพ    กรุงเทพมหานคร
1             1        201  ...           ขท.ปทุมธานี         ปทุมธานี
2             1        202  ...           ขท.ปทุมธานี  พระนครศรีอยุธยา
3             1        300  ...             ขท.อยุธยา  พระนครศรีอยุธยา
4             1        300  ...             ขท.อยุธยา  พระนครศรีอยุธยา
..          ...        ...  ...                   ...              ...
174           9        301  ...           ขท.ปทุมธานี         ปทุมธานี
175           9        301  ...           ขท.ปทุมธานี         ปทุมธานี
176           9        401  ...  ขท.พิเศษระหว่างเมือง  พระนครศรีอยุธยา
177           9        401  ...  ขท.พิเศษระหว่างเมือง         ปทุมธานี
178           9        402  ...  ขท.พิเศษระหว่างเมือง    กรุงเทพมหานคร

[179 rows x 20 columns]

In [ ]:
data_straffic61.isnull() # ตรงไหนเป็นช่องว่างจะขึ้นว่า True ตรงไหนไม่เป็นช่องว่างจะขึ้นว่า False

     ทางหลวงสาย  ตอนควบคุม  ...  แขวงทางหลวง  จังหวัด
0         False      False  ...        False    False
1         False      False  ...        False    False
2         False      False  ...        False    False
3         False      False  ...        False    False
4         False      False  ...        False    False
..          ...        ...  ...          ...      ...
174       False      False  ...        False    False
175       False      False  ...        False    False
176       False      False  ...        False    False
177       False      False  ...        False    False
178       False      False  ...        False    False

[179 rows x 20 columns]

In [ ]:
data_straffic61.isnull().any() # ดูว่าคอลัมน์ไหนมีค่า missing บ้าง

ทางหลวงสาย                           False
ตอนควบคุม                            False
ชื่อสายทาง                           False
จุดสำรวจ                             False
รถยนต์นั่ง (ไม่เกิน 7 คน)            False
รถยนต์นั่ง (เกิน 7 คน)               False
รถโดยสารขนาดเล็ก                     False
รถโดยสารขนาดกลาง                     False
รถโดยสารขนาดใหญ่                     False
รถบรรทุก\nขนาดเล็ก \n(4 ล้อ)         False
รถบรรทุกขนาด 2 เพลา  \n(6 ล้อ)       False
รถบรรทุกขนาด 3 เพลา \n(10 ล้อ)       False
รถบรรทุกพ่วง  (มากกว่า 3 เพลา)       False
รถบรรทุกกึ่งพ่วง (มากกว่า 3 เพลา)    False
รวม                                  False
 % \nของ\nยานยนต์\nหนัก              False
จักรยาน \n2 ล้อ และ จักรยาน 3 ล้อ    False
สามล้อเครื่องและจักรยานยนต์          False
แขวงทางหลวง                          False
จังหวัด                              False
dtype: bool

In [ ]:
data_straffic62 = pd.read_csv(os.path.join(path,'straffic62.csv')) # ไฟล์ที่เราต้องการ
data_straffic62 # print data ดูว่ามันหน้าตาเป็นยังไง

      ทางหลวงสาย  ตอนควบคุม  ...                        แขวงทางหลวง          จังหวัด
0              1        102  ...                         ขท.กรุงเทพ    กรุงเทพมหานคร
1              1        201  ...                        ขท.ปทุมธานี         ปทุมธานี
2              1        202  ...                        ขท.ปทุมธานี  พระนครศรีอยุธยา
3              1        300  ...                          ขท.อยุธยา  พระนครศรีอยุธยา
4              1        300  ...                          ขท.อยุธยา  พระนครศรีอยุธยา
...          ...        ...  ...                                ...              ...
2695        4347        100  ...                            ขท.ตรัง             ตรัง
2696        4348        100  ...                          ขท.กระบี่             ตรัง
2697        4349        100  ...              ขท.สุราษฎร์ธานีที่ 1      สุราษฎร์ธานี
2698        4350        100  ...  ขท.สุราษฎร์ธานีที่ 2 (กาญจนดิษฐ์)     สุราษฎร์ธานี
2699        4363        100  ...                            ขท.ยะลา             ยะลา

[2700 rows x 20 columns]

In [ ]:
data_straffic62.isnull() # ตรงไหนเป็นช่องว่างจะขึ้นว่า True ตรงไหนไม่เป็นช่องว่างจะขึ้นว่า False

      ทางหลวงสาย  ตอนควบคุม  ...  แขวงทางหลวง  จังหวัด
0          False      False  ...        False    False
1          False      False  ...        False    False
2          False      False  ...        False    False
3          False      False  ...        False    False
4          False      False  ...        False    False
...          ...        ...  ...          ...      ...
2695       False      False  ...        False    False
2696       False      False  ...        False    False
2697       False      False  ...        False    False
2698       False      False  ...        False    False
2699       False      False  ...        False    False

[2700 rows x 20 columns]

In [ ]:
data_straffic62.isnull().any() # ดูว่าคอลัมน์ไหนมีค่า missing บ้าง

ทางหลวงสาย                              False
ตอนควบคุม                               False
ชื่อสายทาง                              False
จุดสำรวจ                                False
รถยนต์นั่ง (ไม่เกิน 7 คน)               False
รถยนต์นั่ง (เกิน 7 คน)                  False
รถโดยสารขนาดเล็ก                        False
รถโดยสารขนาดกลาง                        False
รถโดยสารขนาดใหญ่                        False
   รถบรรทุกขนาดเล็ก    ( 4 ล้อ)         False
รถบรรทุกขนาด 2 เพลา  (6 ล้อ)            False
     รถบรรทุกขนาด 3 เพลา (10 ล้อ)       False
   รถบรรทุกพ่วง  (มากกว่า 3 เพลา)       False
   รถบรรทุกกึ่งพ่วง (มากกว่า 3 เพลา)    False
รวม                                     False
   % ของยานยนต์หนัก                     False
จักรยาน 2 ล้อ และ จักรยาน 3 ล้อ         False
สามล้อเครื่องและจักรยานยนต์             False
แขวงทางหลวง                             False
จังหวัด                                 False
dtype: bool

In [ ]:
data_straffic60 = pd.read_csv(os.path.join(path,'straffic60.csv')) # ไฟล์ที่เราต้องการ
data_straffic61 = pd.read_csv(os.path.join(path,'straffic61.csv')) # ไฟล์ที่เราต้องการ
data_straffic62 = pd.read_csv(os.path.join(path,'straffic62.csv')) # ไฟล์ที่เราต้องการ

In [ ]:
data_straffic60.shape

(2691, 20)

In [ ]:
data_straffic61.shape

(179, 20)

In [ ]:
data_straffic62.shape

(2700, 20)

In [ ]:
data_straffic = pd.concat([data_straffic60,data_straffic61,data_straffic62])    # package concat เอาไว้ใช้ในการต่อตารางแนวแกน Y
data_straffic                                                                                           #  ที่เลือกใช้ concat เพราะหัวตารางเหมือนกันหมด ดังนั้นจึงใช้การต่อตารางในแนวแกน Y

      ทางหลวงสาย  ...                        แขวงทางหลวง
0              1  ...                                NaN
1              1  ...                                NaN
2              1  ...                                NaN
3              1  ...                                NaN
4              1  ...                                NaN
...          ...  ...                                ...
2695        4347  ...                            ขท.ตรัง
2696        4348  ...                          ขท.กระบี่
2697        4349  ...              ขท.สุราษฎร์ธานีที่ 1
2698        4350  ...  ขท.สุราษฎร์ธานีที่ 2 (กาญจนดิษฐ์)
2699        4363  ...                            ขท.ยะลา

[5570 rows x 28 columns]